name: Android Lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: chmod +x ./gradlew

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
            ~/.gradle/build-cache
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts', '**/gradle.lockfile') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run lint only on changed modules
        run: |
          changed_modules=$(git diff --name-only origin/master...HEAD | grep 'build.gradle' | sed 's|/build.gradle.*||' | sort -u)
          echo "Changed modules: $changed_modules"
          if [ -z "$changed_modules" ]; then
            echo "No modules changed, running lint globally"
            ./gradlew lint --no-daemon --stacktrace
          else
            for module in $changed_modules; do
              echo "Running lint for module: $module"
              ./gradlew :$module:lint --no-daemon --stacktrace || exit 1
            done
          fi
